/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AgendaMedica;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2019122760249
 */
public class FMAgendaMedica extends javax.swing.JFrame {

    /**
     * Creates new form FMAgendaMedica
     */
    public FMAgendaMedica() {
        initComponents();
        PnPlano.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        ButGConsulta = new javax.swing.ButtonGroup();
        PopupMenuResumo = new javax.swing.JPopupMenu();
        MnInserir = new javax.swing.JMenuItem();
        MnExcluir = new javax.swing.JMenuItem();
        LBAgenda = new javax.swing.JLabel();
        PNDados = new javax.swing.JPanel();
        LBNome = new javax.swing.JLabel();
        LBEmail = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        PNConsultas = new javax.swing.JPanel();
        RButSus = new javax.swing.JRadioButton();
        RButPlano = new javax.swing.JRadioButton();
        LBEspecialidade = new javax.swing.JLabel();
        CmBoxEspecialidade = new javax.swing.JComboBox<>();
        LBHoraIni = new javax.swing.JLabel();
        LBHoraFim = new javax.swing.JLabel();
        SpiHoraIni = new javax.swing.JSpinner();
        SpiHoraFim = new javax.swing.JSpinner();
        ButInserir = new javax.swing.JButton();
        ButLimpar = new javax.swing.JButton();
        PNResumo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbResumo = new javax.swing.JTable();
        PnPlano = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtNomePlano = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        MnInserir.setText("Inserir");
        MnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButInserirActionPerformed(evt);
            }
        });
        PopupMenuResumo.add(MnInserir);

        MnExcluir.setText("Excluir");
        MnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnExcluirActionPerformed(evt);
            }
        });
        PopupMenuResumo.add(MnExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBAgenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBAgenda.setForeground(new java.awt.Color(0, 51, 255));
        LBAgenda.setText("Agenda Médica");

        PNDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        LBNome.setText("Nome");

        LBEmail.setText("E-mail");

        javax.swing.GroupLayout PNDadosLayout = new javax.swing.GroupLayout(PNDados);
        PNDados.setLayout(PNDadosLayout);
        PNDadosLayout.setHorizontalGroup(
            PNDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNDadosLayout.createSequentialGroup()
                        .addComponent(LBEmail)
                        .addGap(18, 18, 18))
                    .addGroup(PNDadosLayout.createSequentialGroup()
                        .addComponent(LBNome)
                        .addGap(21, 21, 21)))
                .addGroup(PNDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TxtNome)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNDadosLayout.setVerticalGroup(
            PNDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBNome)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(PNDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBEmail)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PNConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder("Consultas"));

        ButGConsulta.add(RButSus);
        RButSus.setMnemonic('S');
        RButSus.setText("SUS");
        RButSus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButSusActionPerformed(evt);
            }
        });

        ButGConsulta.add(RButPlano);
        RButPlano.setMnemonic('P');
        RButPlano.setText("Plano de Saúde");
        RButPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButSusActionPerformed(evt);
            }
        });

        LBEspecialidade.setText("Especialidade");

        LBHoraIni.setText("Hora Início");

        LBHoraFim.setText("Hora Fim");

        SpiHoraIni.setModel(new javax.swing.SpinnerNumberModel(10, 7, 22, 1));
        SpiHoraIni.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpiHoraIniStateChanged(evt);
            }
        });

        SpiHoraFim.setModel(new javax.swing.SpinnerNumberModel(11, 7, 22, 1));
        SpiHoraFim.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpiHoraFimStateChanged(evt);
            }
        });

        javax.swing.GroupLayout PNConsultasLayout = new javax.swing.GroupLayout(PNConsultas);
        PNConsultas.setLayout(PNConsultasLayout);
        PNConsultasLayout.setHorizontalGroup(
            PNConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNConsultasLayout.createSequentialGroup()
                        .addComponent(RButSus)
                        .addGap(18, 18, 18)
                        .addComponent(RButPlano))
                    .addGroup(PNConsultasLayout.createSequentialGroup()
                        .addComponent(LBEspecialidade)
                        .addGap(18, 18, 18)
                        .addComponent(CmBoxEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNConsultasLayout.createSequentialGroup()
                        .addComponent(LBHoraIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpiHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(LBHoraFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SpiHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        PNConsultasLayout.setVerticalGroup(
            PNConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RButSus)
                    .addComponent(RButPlano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBEspecialidade)
                    .addComponent(CmBoxEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PNConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBHoraIni)
                    .addComponent(LBHoraFim)
                    .addComponent(SpiHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpiHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        ButInserir.setText("Inserir");
        ButInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButInserirActionPerformed(evt);
            }
        });

        ButLimpar.setText("Limpar");
        ButLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLimparActionPerformed(evt);
            }
        });

        PNResumo.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo"));
        PNResumo.setLayout(new java.awt.BorderLayout());

        TbResumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "E-mail", "SUS/Plano", "Especialidade", "Nome do Plano"
            }
        ));
        TbResumo.setComponentPopupMenu(PopupMenuResumo);
        jScrollPane4.setViewportView(TbResumo);

        PNResumo.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        PnPlano.setBorder(javax.swing.BorderFactory.createTitledBorder("Plano de Saúde"));

        jLabel1.setText("Nome do Plano");

        javax.swing.GroupLayout PnPlanoLayout = new javax.swing.GroupLayout(PnPlano);
        PnPlano.setLayout(PnPlanoLayout);
        PnPlanoLayout.setHorizontalGroup(
            PnPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPlanoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TxtNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnPlanoLayout.setVerticalGroup(
            PnPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPlanoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNomePlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PNResumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PnPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBAgenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PNConsultas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PNDados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(ButInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(ButLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PnPlano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButInserir)
                    .addComponent(ButLimpar))
                .addGap(18, 18, 18)
                .addComponent(PNResumo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RButSusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButSusActionPerformed
        if(RButSus.isSelected()){
            PnPlano.setVisible(false);
            
            SpiHoraIni.setValue(10);
            SpiHoraFim.setValue(11);
            
            CmBoxEspecialidade.removeAllItems();
            CmBoxEspecialidade.addItem("Clínico Geral");
            CmBoxEspecialidade.addItem("Psicólogo");
            CmBoxEspecialidade.addItem("Pediatra");
        }
        else if(RButPlano.isSelected()){
            PnPlano.setVisible(true);
            
            SpiHoraIni.setValue(10);
            SpiHoraFim.setValue(11);
            
            CmBoxEspecialidade.removeAllItems();
            CmBoxEspecialidade.addItem("Ortopedista");
            CmBoxEspecialidade.addItem("Neurologista");
            CmBoxEspecialidade.addItem("Cirurgia Cardíaca");
        }
    }//GEN-LAST:event_RButSusActionPerformed

    private void ButLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLimparActionPerformed
        TxtNome.setText("");
        TxtEmail.setText("");
        SpiHoraIni.setValue(10);
        SpiHoraFim.setValue(11);
        if(PnPlano.isVisible()){
            TxtNomePlano.setText("");
        }
        
    }//GEN-LAST:event_ButLimparActionPerformed

    private void ButInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButInserirActionPerformed
        String nome = TxtNome.getText();
        String email = TxtEmail.getText();
        String susPlan = "";
        String especialidade = CmBoxEspecialidade.getSelectedItem().toString();
        String plano = TxtNomePlano.getText();
        
        if (ButGConsulta.getSelection().getMnemonic() == 'S'){
            susPlan = "SUS";
        }
        
        if (ButGConsulta.getSelection().getMnemonic() == 'P'){
            susPlan = "Plano de Saúde";
        }
        
        inserirTabela(nome,email,susPlan,especialidade,plano);
        
    }//GEN-LAST:event_ButInserirActionPerformed

    private void MnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnExcluirActionPerformed
        int linha = TbResumo.getSelectedRow();
        if(linha >= 0){
            ((DefaultTableModel) TbResumo.getModel()).removeRow(linha);
        }
    }//GEN-LAST:event_MnExcluirActionPerformed

    private void SpiHoraIniStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpiHoraIniStateChanged
        int spinIni = Integer.parseInt(SpiHoraIni.getValue().toString());

        if(spinIni > 10){
            if(CmBoxEspecialidade.getSelectedItem() == "Ortopedista"){
                SpiHoraFim.setValue(Integer.parseInt(SpiHoraFim.getValue().toString()) + 1);
            }
            else if(CmBoxEspecialidade.getSelectedItem() == "Neurologista"){
                SpiHoraFim.setValue(Integer.parseInt(SpiHoraFim.getValue().toString()) + 2); 
            }
            else if(CmBoxEspecialidade.getSelectedItem() == "Cirurgia Cardíaca"){
                SpiHoraFim.setValue(Integer.parseInt(SpiHoraFim.getValue().toString()) + 4);
            }
            else if(CmBoxEspecialidade.getSelectedItem() == "Clínico Geral"){
                SpiHoraFim.setValue(Integer.parseInt(SpiHoraFim.getValue().toString()) + 1);
            }
            else if(CmBoxEspecialidade.getSelectedItem() == "Pediatra"){
                SpiHoraFim.setValue(Integer.parseInt(SpiHoraFim.getValue().toString()) + 1); 
            }
            else if(CmBoxEspecialidade.getSelectedItem() == "Psicólogo"){
                SpiHoraFim.setValue(Integer.parseInt(SpiHoraFim.getValue().toString()) + 2);
            }

        }

        SpiHoraIni.setValue(spinIni);
    }//GEN-LAST:event_SpiHoraIniStateChanged

    private void SpiHoraFimStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpiHoraFimStateChanged
        int spinFim = Integer.parseInt(SpiHoraFim.getValue().toString()); 
        
        SpiHoraFim.setValue(spinFim);  
    }//GEN-LAST:event_SpiHoraFimStateChanged
    private void inserirTabela (String nome, String email, String plano, String especialidade, String nomePlan){
        ((DefaultTableModel) TbResumo.getModel()).addRow(new Object[0]);
        
        int col = 0;
        int linha = TbResumo.getRowCount() - 1;
        
        TbResumo.setValueAt(nome, linha, col++);
        TbResumo.setValueAt(email, linha, col++);
        TbResumo.setValueAt(plano, linha, col++);
        TbResumo.setValueAt(especialidade, linha, col++);
        TbResumo.setValueAt(nomePlan, linha, col++);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMAgendaMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMAgendaMedica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButGConsulta;
    private javax.swing.JButton ButInserir;
    private javax.swing.JButton ButLimpar;
    private javax.swing.JComboBox<String> CmBoxEspecialidade;
    private javax.swing.JLabel LBAgenda;
    private javax.swing.JLabel LBEmail;
    private javax.swing.JLabel LBEspecialidade;
    private javax.swing.JLabel LBHoraFim;
    private javax.swing.JLabel LBHoraIni;
    private javax.swing.JLabel LBNome;
    private javax.swing.JMenuItem MnExcluir;
    private javax.swing.JMenuItem MnInserir;
    private javax.swing.JPanel PNConsultas;
    private javax.swing.JPanel PNDados;
    private javax.swing.JPanel PNResumo;
    private javax.swing.JPanel PnPlano;
    private javax.swing.JPopupMenu PopupMenuResumo;
    private javax.swing.JRadioButton RButPlano;
    private javax.swing.JRadioButton RButSus;
    private javax.swing.JSpinner SpiHoraFim;
    private javax.swing.JSpinner SpiHoraIni;
    private javax.swing.JTable TbResumo;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNomePlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
